version: "3.8"
services:
  mvp-processor:
    container_name: mvp-processor
    build: .
    ports:
      - "5000:5000"
    restart: always
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    volumes: [".:/app"]
